### ISSUE TITLE
Elac ver4 error

### ISSUE THREAD

**Issue by SiLPHER401** [samyuu/EvenMoreLegitArcadeController#10]
When i am using elac ver3 everything is all right , but after changing it to elac ver4 the diva.exe crash .I opened diva.exe then open the elac.exe , after a few sec it crash . I didnt touch any .ini files and everything is the same , all encoded with UTF-8 .Please tell me what is happening , is it my pc problem or the apps error .

**Comment by samyuu** [comment]
These kind of problems can be quite difficult to diagnose;
If possible please try to disable all components inside the `components.ini` file and then enable them one by one so we can narrow down the source of this problem.

Otherwise noteworthy when using newer versions is to re-prepatch an *unedited* `diva.exe` as well as making sure you are not using the config files from previous versions as their structures might have changed.
